<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="applicable-device" content="pc">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta name="keywords" content="宠爱之家,宠物,宠物网,宠物训练,宠物新闻,狗狗,猫猫,宠物狗,宠物猫,宠物鼠,宠物兔">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <title>宠爱之家-分享潮流宠物资讯,打造宠物行业门户</title>
    <link rel="stylesheet" href="/css/media/swiper.min.css">
    <link rel="stylesheet" href="/css/media/video-js.min.css">
    <link rel="stylesheet" href="/css/media/public.css">
    <link rel="stylesheet" href="/css/media/base.css">
    <link rel="stylesheet" href="/css/media/index/index.css">
</head>
<body>
    <!--  swiper bar  -->
    <div class="header">
        <!--  swiper  -->
        <div class="big-banner">
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    <div class="swiper-slide"><img src="/img/media/index/1.png" style="width: 100%;height: 100%;" alt=""></div>
                    <div class="swiper-slide"><img src="/img/media/index/5.png" style="width: 100%;height: 100%;" alt=""></div>
                    <div class="swiper-slide"><img src="/img/media/index/4.png" style="width: 100%;height: 100%;" alt=""></div>
                    <div class="swiper-slide"><img src="/img/media/index/2.png" style="width: 100%;height: 100%;" alt=""></div>
                    <!--<div class="swiper-slide"><img src="images/index/3.png" style="width: 100%;height: 100%;" alt=""></div>-->
                </div>
                <!-- Add Pagination -->
                <div class="swiper-pagination"></div>
                <!-- Add Arrows -->
                <div class="big-next swiper-button-next"></div>
                <div class="big-prev swiper-button-prev"></div>
            </div>
        </div>
        <!--  nav bar  -->
        <div class="nav-bar">
            <div class="main">
                <a href="http://www.pettap.cn/" class="logo">宠爱之家</a>
                <ul class="nav">
                    <li class="cur"><a href="/index/index">首页</a></li>
                    <li class="head-about"><a href="/index/news">宠爱动态</a></li>
                    <li class="head-about"><a href="/index/rescue">宠爱救助站</a></li>
                    <li class="head-about"><a href="javascript:alert('程序小哥哥正在努力加紧中！');">宠爱商城</a></li>
                    <li class="head-about"><a href="/index/about">关于宠爱</a></li>
                    <!--<li class="head-about"><a href="javascript:void(0);">加入宠爱</a></li>-->
                </ul>
            </div>
        </div>
    </div>
    <!--  news  -->
    <div class="news-tab center clearfix">

        <!--<div class="fl andriod-down pr">
            <img src="images/index/andriod.png" alt="">
            <div class="down-mask hide">
                <p class="down-mask-t">IOS下载</p>
                <img src="images/index/ewm.png" alt="">
                <a class="down-btn" href="javascript:void(0);">点击下载</a>
            </div>
        </div>-->
        <div class="tit">宠爱家园</div>
        <div class="staff-l video-box fl">
            <video id="my-video" class="video-js" controls preload="auto" width="960" height="480" poster="/img/media/index/video-bg.png" data-setup="{}">
                <source src="/img/media/video/chongaizhijia.mp4" type="video/mp4">
            </video>
        </div>
        <div class="fr ios-down pr">
            <img src="/img/media/index/ios.png" alt="">
            <div class="down-mask">
                <p class="down-mask-t">Android下载</p>
                <img class="down-mask-t-img" src="/img/media/index/ewm.png" width="140" height="140" alt="">
                <a class="down-btn" href="javascript:void(0);">点击下载</a>
            </div>
        </div>
    </div>
    <!--  family  -->
    <div class="staff-mien center clearfix">
        <div class="news-trends fl">
            <div class="tit">宠爱新闻<a href="/index/news" class="fr">查看更多</a></div>
            <ul>
                <?php foreach ($newsData as $key=>$value): ?>
                <li>
                    <a href="/index/detail?id=<?=$value['id']?>" target="_blank">
                        <div class="date"><span><?=date("m-d",$value['create_time'])?></span><?=date("Y",$value['create_time'])?></div>
                        <div class="content">
                            <p><?=$value['title']?></p>
                            <span><?=$value['content']?></span>
                        </div>
                    </a>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="community fr">
            <div class="tit">宠爱社区</div>
            <div class="staff-r">
                <div class="top clearfix">
                    <div class="top-l fl pr">
                        <div class="rescue">
                            <p class="rescue-title">爱心观察员</p>
                            <p class="rescue-text">想知道救助过的小动物们后续？请戳：</p>
                        </div>
                    </div>
                    <div class="top-r fr pr">
                        <div class="rescue r-shop">
                            <p class="rescue-title">宠爱商城</p>
                            <p class="rescue-text">想给萌宠最好的宠爱？请戳：</p>
                        </div>
                    </div>
                </div>
                <div class="bottom pr">
                    <div class="rescue r-hospital">
                        <p class="rescue-title">萌宠医院</p>
                        <p class="rescue-text">宠爱之家合作医院，爱宠生病不要慌！请戳：</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--  contact us  -->
    <div class="contact-us">
        <div class="center">
            <div class="ewm"><img src="/img/media/index/ewm.png">宠爱之家官方公众号</div>
            <div class="adress">
                <div class="tit">深圳总公司：</div>
                <p class="ad1">广东省深圳市南山区兰香一街海王星辰总部大厦13楼
                    <a href="javascript:;" class="phone">电话：+0755-86659665</a>
                    <span class="email">电子邮箱：<a href="mailto:duan@mail.zhishengwh.com">duan@mail.zhishengwh.com</a></span>
                </p>
            </div>
        </div>
    </div>

    <!--  回到顶部  -->
    <a class="go-top">返回顶部</a>

    <!--  footer  -->
    <div class="footer">Copyright © 2017 Shenzhen Zhisheng Cultural Innovation Co., Ltd. All Rights Reserved<a href="http://www.miitbeian.gov.cn" target="_blank" rel="nofollow">粤ICP备18083935号</a></div>

    <script src="/js/jquery.js"></script>
    <script src="/js/swiper.min.js"></script>
    <script src="/js/video.min.js"></script>
    <script src="/js/media.js"></script>
    <script>
        //swiper
        var swiper = new Swiper('.swiper-container', {
            navigation: {
                nextEl: '.big-next',
                prevEl: '.big-prev',
            },
            loop: true,
            autoplay: {
                delay: 4000
            },//可选选项，自动滑动
            speed: 600,
            pagination: {
                el: '.swiper-pagination',
            }
        });
        //video
        var myPlayer = videojs('my-video');
        videojs("my-video").ready(function(){
            var myPlayer = this;
            //myPlayer.play();
        });
    </script>
</body>
</html>
