<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="applicable-device" content="pc">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta name="keywords" content="宠爱动态详情，宠爱动态，宠爱宠物详情">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <title>宠爱之家-分享潮流宠物资讯,打造宠物行业门户</title>
    <link rel="stylesheet" href="/css/media/public.css">
    <link rel="stylesheet" href="/css/media/base.css">
    <link rel="stylesheet" href="/css/media/detail/index.css?v=2018113">
</head>
<body>
    <div class="header about-top news-top">
        <!--  header  -->
        <div class="nav-bar">
            <div class="main">
                <a href="http://www.pettap.cn/" class="logo">宠爱之家</a>
                <ul class="nav">
                    <li class=""><a href="/index/index">首页</a></li>
                    <li class="head-about cur"><a href="/index/news">宠爱动态</a></li>
                    <li class="head-about"><a href="/index/rescue">宠爱救助站</a></li>
                    <li class="head-about"><a href="javascript:alert('程序小哥哥正在努力加紧中！');">宠爱商城</a></li>
                    <li class="head-about"><a href="/index/about">关于宠爱</a></li>
                    <!--<li class="head-about"><a href="javascript:void(0);">加入宠爱</a></li>-->
                </ul>
            </div>
        </div>
    </div>
    <!--  detail  -->
    <div class="detail-box center">
        <div class="tit"><a href="/index/index">宠爱之家</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/index/news">新闻动态</a>&nbsp;&nbsp;&gt;&nbsp;&nbsp;文章详情</div>
        <h1 class="newsdtit"><?=$oneData->title?></h1>
        <div class="dete">发布日期：<a><?=date("Y-m-d",$oneData->create_time)?></a><span class="content_from">作者：<a><?=$oneData->author?></a></span><span class="content_from">来源：<a href="/index/index">宠爱之家官网</a></span></div>
        <div class="detail-body">
            <?=htmlspecialchars_decode($oneData->content)?>
        </div>
        <div class="unauthorized">
            <p>以上内容均为宠爱之家原创稿件，未经授权，谢绝转载，如需转载请联系本站并保留以上全部内容。更多精彩，尽在宠爱之家！注：文章所有图片均来自于网络</p>
        </div>
    </div>

    <!--  contact us  -->
    <div class="contact-us">
        <div class="center">
            <div class="ewm"><img src="/img/media/index/ewm.png">宠爱之家官方公众号</div>
            <div class="adress">
                <div class="tit">深圳总公司：</div>
                <p class="ad1">广东省深圳市南山区兰香一街海王星辰总部大厦13楼
                    <a href="javascript:;" class="phone">电话：+0755-86659665</a>
                    <span class="email">电子邮箱：<a href="mailto:duan@mail.zhishengwh.com">duan@mail.zhishengwh.com</a></span>
                </p>
            </div>
        </div>
    </div>

    <!--  回到顶部  -->
    <a class="go-top">返回顶部</a>

    <!--  footer  -->
    <div class="footer">Copyright © 2017 Shenzhen Zhisheng Cultural Innovation Co., Ltd. All Rights Reserved<a href="http://www.miitbeian.gov.cn" target="_blank" rel="nofollow">粤ICP备18083935号</a></div>

    <script src="/js/jquery.js"></script>
    <script src="/js/media.js"></script>
</body>
</html>
