<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="applicable-device" content="pc">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta name="keywords" content="宠爱资讯，宠爱新闻，宠爱动态">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <title>宠爱之家-分享潮流宠物资讯,打造宠物行业门户</title>
    <link rel="stylesheet" href="/css/media/public.css">
    <link rel="stylesheet" href="/css/media/base.css">
    <link rel="stylesheet" href="/css/media/news/index.css">
    <link href="/layui/css/layui.css" rel="stylesheet" media="all" />
    <style>#pages{margin: 10px 10px;line-height: 34px;}#pages a:nth-last-of-type(1){margin-right: 10px;}</style>
</head>
<body>
    <div class="header about-top news-top">
        <!--  header  -->
        <div class="nav-bar">
            <div class="main">
                <a href="http://www.pettap.cn/" class="logo">宠爱之家</a>
                <ul class="nav">
                    <li class=""><a href="/index/index">首页</a></li>
                    <li class="head-about cur"><a href="/index/news">宠爱动态</a></li>
                    <li class="head-about"><a href="/index/rescue">宠爱救助站</a></li>
                    <li class="head-about"><a href="javascript:alert('程序小哥哥正在努力加紧中！');">宠爱商城</a></li>
                    <li class="head-about"><a href="/index/about">关于宠爱</a></li>
                    <!--<li class="head-about"><a href="javascript:void(0);">加入宠爱</a></li>-->
                </ul>
            </div>
        </div>
    </div>
    <!--  news list  -->
    <div class="news-list center">
        <div class="tit">宠爱动态</div>
        <ul class="news-item">
            <?php foreach ($page->items as $key=>$value): ?>
            <li>
                <span class="pic"><img src="http://<?=server('SERVER_ADDR')?>/upload/<?=json_decode($value->pic,true)[0]?>"></span>
                <div class="item-pos">
                    <span class="date"><?=date("Y/m/d",$value->create_time)?></span>
                    <p class="title"><?=$value->title?></p>
                    <p class="des"><?=$value->content?></p>
                    <a href="/index/detail?id=<?=$value->id?>">查看详情</a>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>

        <div class="pagination">
        <?=showPage($page,"/index/news")?>
<!--            <a href="javascript:void(0);" class="prev">上一页</a>-->
<!--            <a href="javascript:void(0);" class="active">1</a>-->
<!--            <a href="javascript:void(0);">2</a>-->
<!--            <a href="javascript:void(0);">3</a>-->
<!--            <a href="javascript:void(0);">4</a>-->
<!--            <a href="javascript:void(0);" class="next">下一页</a>-->
        </div>
    </div>
    <!--  contact us  -->
    <div class="contact-us">
        <div class="center">
            <div class="ewm"><img src="/img/media/index/ewm.png">宠爱之家官方公众号</div>
            <div class="adress">
                <div class="tit">深圳总公司：</div>
                <p class="ad1">广东省深圳市南山区兰香一街海王星辰总部大厦13楼
                    <a href="javascript:;" class="phone">电话：+0755-86659665</a>
                    <span class="email">电子邮箱：<a href="mailto:duan@mail.zhishengwh.com">duan@mail.zhishengwh.com</a></span>
                </p>
            </div>
        </div>
    </div>

    <!--  回到顶部  -->
    <a class="go-top">返回顶部</a>

    <!--  footer  -->
    <div class="footer">Copyright © 2017 Shenzhen Zhisheng Cultural Innovation Co., Ltd. All Rights Reserved<a href="http://www.miitbeian.gov.cn" target="_blank" rel="nofollow">粤ICP备18083935号</a></div>

    <script src="/js/jquery.js"></script>
    <script src="/js/media.js"></script>
    <script src="/layui/layui.all.js"></script>

</body>
</html>
