<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="applicable-device" content="pc">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta name="keywords" content="宠爱宠物救助站入驻信息，宠爱宠物救助站合作，宠物救助站信息">
    <meta name="description" content="宠爱之家作为宠物行业领先门户网站,主要提供和分享新潮的宠物行业新闻,宠物趣事,逗趣的宠物图片,视频,直播等全面的宠物医疗宠物养护宠物训练宠物美容等知识.">
    <title>宠爱之家-分享潮流宠物资讯,打造宠物行业门户</title>
    <link rel="stylesheet" href="/css/media/swiper.min.css">
    <link rel="stylesheet" href="/css/media/public.css">
    <link rel="stylesheet" href="/css/media/base.css">
    <link rel="stylesheet" href="/css/media/rescueinfo/index.css">
</head>
<body>
<div class="header">
    <!--  header  -->
    <div class="nav-bar">
        <div class="main">
            <a href="http://www.pettap.cn/" class="logo">宠爱之家</a>
            <ul class="nav">
                <!--<li class=""><a href="../index.html">首页</a></li>
                <li class="head-about"><a href="../news.html">宠爱动态</a></li>
                <li class="head-about cur"><a href="../rescue.html">宠爱救助站</a></li>
                <li class="head-about"><a href="javascript:alert('程序小哥哥正在努力加紧中！');">宠爱商城</a></li>-->
                <li class="head-about"><a href="javascript:void(0);">加入宠爱之家官方救助站平台</a></li>
                <!--<li class="head-about"><a href="javascript:void(0);">加入宠爱</a></li>-->
            </ul>
            <ul class="out-btn">
                <li><span>欢迎&nbsp;</span><span>17688830262</span></li>
                <li>|</li>
                <li><a class="btn" href="/index/login">退出</a></li>
            </ul>
        </div>
    </div>
</div>
<!--  swiper  -->
<div class="swiper-box">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide"><img src="/img/media/rescueinfo/banner1.jpg" width="100%" height="180" alt=""></div>
            <div class="swiper-slide"><img src="/img/media/rescueinfo/banner2.jpg" width="100%" height="180" alt=""></div>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
        <!-- Add Arrows -->
        <!--<div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>-->
    </div>
</div>
<!--  提交信息  -->
<div class="info-box center">
    <div class="tit">用户提交信息</div>
    <input type="hidden" id="u_m_id" name="id" value="<?=$oneData->id?>" readonly>
    <div class="one info">
        <div>一、是否是经营性救助站(必填)</div>
        <div class="clearfix">
            <div class="radio-inline fl radio-filed">
                <input type="radio" name="commercial" value="经营性" <?php if($oneData->commercial == '经营性'){ echo 'checked'; } ?> readonly>
                <label for="">经营性</label>
            </div>
            <div class="radio-inline fl radio-filed">
                <input type="radio" name="commercial" value="非经营性" <?php if($oneData->commercial == '非经营性'){ echo 'checked'; } ?> readonly>
                <label for="">非经营性</label>
            </div>
        </div>
    </div>
    <div class="two info">
        <div>二、信息输入(必填)</div>
        <div class="clearfix">
            <div class="radio-inline fl clearfix">
                <span class="input-t fl">姓名：</span>
                <input type="text" class="input-b fl" id="uname" placeholder="请输入姓名" value="<?=$oneData->real_name?>" readonly>
            </div>
            <div class="radio-inline fl clearfix">
                <span class="input-t fl">手机号：</span>
                <input type="text" class="input-b fl" id="mobile" placeholder="请输入手机号码" value="<?=$oneData->mobile_num?>" readonly>
            </div>
            <div class="radio-inline fl clearfix">
                <span class="input-t fl">身份证号：</span>
                <input type="text" class="input-b fl" id="card" placeholder="请输入身份证号码" value="<?=$oneData->id_card?>" readonly>
            </div>
            <div class="radio-inline fl clearfix sex-inline">
                <span class="input-t fl">性别：</span>
                <div class="fl sex">
                    <input type="radio" name="sex" value="男" <?php if($oneData->sex == '男'){ echo 'checked'; } ?>  readonly>
                    <label for="">男</label>
                </div>
                <div class="fl sex">
                    <input type="radio" name="sex" value="女" <?php if($oneData->sex == '女'){ echo 'checked'; } ?> readonly>
                    <label for="">女</label>
                </div>
            </div>
            <div class="radio-inline fl clearfix">
                <span class="input-t fl">所在地：</span>
                <div class="form-inline fl">
                    <input type="text" class="input-b fl" id="address" placeholder="请输入详细地址如：XXX省XXX市XXX区XXX街XXX号" value="<?=$oneData->address?>" readonly>
                </div>
            </div>

            <div class="radio-inline fl clearfix textarea-box">
                <span class="input-t fl">说明：</span>
                <textarea class="textarea" id="info" placeholder="组织&#10团体介绍&#10经营&#10服务范围" readonly><?=$oneData->info?></textarea>
            </div>
        </div>
    </div>
    <div class="th info">
        <div>三、上传图片(必填)</div>
        <div class="radio-inline clearfix pr three">
            <span class="input-t fl i-text">身份证正面：</span>
            <input type="file" accept="image/*" class="input-img" readonly>
            <div class="upload"><img class="book-pic" src="<?=$oneData->idcard?>" alt=""></div>
            <input type="hidden" id="idcard" name="idcard" value="<?=$oneData->idcard?>">
        </div>
        <div class="radio-inline clearfix">
            <span class="input-t fl i-text">示例图：</span>
            <img class="example-pic fl" src="/img/media/rescueinfo/sfz1.jpg" alt="">
        </div>
        <div class="radio-inline clearfix pr three">
            <span class="input-t fl i-text">身份证反面：</span>
            <input type="file"  accept="image/*" class="input-img" readonly>
            <div class="upload"><img class="book-pic" src="<?=$oneData->reidcard?>" alt=""></div>
            <input type="hidden" id="reidcard" name="reidcard" value="<?=$oneData->reidcard?>">
        </div>
        <div class="radio-inline clearfix">
            <span class="input-t fl i-text">示例图：</span>
            <img class="example-pic fl" src="/img/media/rescueinfo/sfz2.jpg" alt="">
        </div>
        <div class="radio-inline clearfix pr three">
            <span class="input-t fl i-text">手持身份证：</span>
            <input type="file"  accept="image/*" class="input-img" readonly>
            <div class="upload"><img class="book-pic" src="<?=$oneData->handidcard?>" alt=""></div>
            <input type="hidden" id="handidcard" name="handidcard" value="<?=$oneData->handidcard?>">
        </div>
        <div class="radio-inline clearfix">
            <span class="input-t fl i-text">示例图：</span>
            <img class="example-pic fl" src="/img/media/rescueinfo/sfz3.jpg" alt="">
        </div>

        <?php if($oneData->commercial == '非经营性'): ?>
            <div class="radio-inline clearfix pr three license" id="license" style="display: none;">
                <span class="input-t fl i-text">营业执照图：</span>
                <input type="file" accept="image/*" class="input-img" readonly>
                <div class="upload"><img class="book-pic" src="/img/media/rescueinfo/upload.png" alt=""></div>
                <input type="hidden" id="permit" name="permit" value="" disabled="disabled">
            </div>
        <?php else: ?>
            <div class="radio-inline clearfix pr three license" id="license">
                <span class="input-t fl i-text">营业执照图：</span>
                <input type="file"  accept="image/*" class="input-img" readonly>
                <div class="upload"><img class="book-pic" src="<?=$oneData->permit?>" alt=""></div>
                <input type="hidden" id="permit" name="permit" value="<?=$oneData->permit?>">
            </div>
        <?php endif; ?>
        <div class="radio-inline clearfix three license">
            <span class="input-t fl i-text">场地照片图：</span>
            <div class="pr field">
                <input type="file"  accept="image/*" class="input-img field-img" readonly>
                <div class="upload field-img"><img class="book-pic" src="<?=$oneData->field1?>" alt=""></div>
                <input type="hidden" id="field1" name="field1" value="<?=$oneData->field1?>">
            </div>
            <div class="pr field">
                <input type="file"  accept="image/*" class="input-img field-img" readonly>
                <div class="upload field-img"><img class="book-pic" src="<?=$oneData->field2?>" alt=""></div>
                <input type="hidden" id="field2" name="field2" value="<?=$oneData->field2?>">
            </div>
            <div class="pr field">
                <input type="file"  accept="image/*" class="input-img field-img" readonly>
                <div class="upload field-img"><img class="book-pic" src="<?=$oneData->field3?>" alt=""></div>
                <input type="hidden" id="field3" name="field3" value="<?=$oneData->field3?>">
            </div>
            <div class="pr field">
                <input type="file"  accept="image/*" class="input-img field-img" readonly>
                <div class="upload field-img"><img class="book-pic" src="<?=$oneData->field4?>" alt=""></div>
                <input type="hidden" id="field4" name="field4" value="<?=$oneData->field4?>">
            </div>
        </div>
    </div>
    <button class="sub-btn" id="sbtn" onclick="window.history.back()">返回</button>
</div>

<!--  回到顶部  -->
<a class="go-top">返回顶部</a>

<!--  footer  -->
<div class="footer">
    <div class="center">
        <p><a href="javascript:void(0);">Copyright © 2017 Shenzhen Zhisheng Cultural Innovation Co., Ltd. All Rights Reserved</a></p>
    </div>
</div>

<script src="/js/jquery.js"></script>
<script src="/js/swiper.min.js"></script>
<script src="/js/ajaxfileupload.js"></script>
<script src="/js/media.js"></script>
<script>
    $(function(){
        //轮播
        var swiper = new Swiper('.swiper-container', {
            loop: true,
            autoplay: {
                delay: 4000
            },
            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            }
        });
    });
</script>
</body>
</html>
